[build]
  # Build settings
  publish = "frontend"
  command = "echo 'No build needed - static HTML/JS app'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  # Cache static assets
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache HTML with shorter duration
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  # Handle SPA routing (redirect all routes to index.html)
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # Local development settings
  command = "python -m http.server 8000"
  targetPort = 8000
  port = 8888
  publish = "frontend" 